version: "3.3"

services:
  seedcloud:
    image: bruteforcemovable/seedcloud:latest
    volumes:
      - "./htdocs:/app"
    links:
      - part1dumper
      - bfmsql
    ports: 
      - 8080:8080
    volumes:
      - "./htdocs:/app"
      - "./site.conf:/etc/nginx/conf.d/default.conf"
  part1dumper:
    image: bruteforcemovable/part1dumperbackend:latest
    ports:
      - 8081:80
    links:
      - bfmsql
  bfmsql:
    container_name: flask_mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'liK0sDLA'
    volumes:
      - ./mysql:/var/lib/mysql
